### ISSUE TITLE
Hard coded paths

### ISSUE THREAD

**Issue by ilyash** [sindresorhus/os-homedir#4]
At least for Linux this will give wrong results (probably for BSD/Mac too). If `HOME` is not set, `getpwent()` should probably be used to get the home directory.

**Comment by sindresorhus** [comment]
> At least for Linux this will give wrong results (probably for BSD/Mac too).

Can you elaborate and provide some proof on that?

**Comment by ilyash** [comment]
The assumption that home directories are all under `/home` directory is wrong.

Place in `/var/tmp/index.js` the following file:

```
function homedir() {
	var env = process.env;
	var home = env.HOME;
	var user = env.LOGNAME || env.USER || env.LNAME || env.USERNAME;

	if (process.platform === 'win32') {
		return env.USERPROFILE || env.HOMEDRIVE + env.HOMEPATH || home || null;
	}

	if (process.platform === 'darwin') {
		return home || (user ? '/Users/' + user : null);
	}

	if (process.platform === 'linux') {
		return home || (process.getuid() === 0 ? '/root' : (user ? '/home/' + user : null));
	}

	return home || null;
}

console.log(homedir());

```

The home of `kdm` user is `/var/lib/kdm` on my machine (seen in `/etc/passwd`).
Issue:
```
su - kdm -s /bin/bash
env -u HOME nodejs /var/tmp/index.js
```
and get
`/home/kdm`

**Comment by Roguelazer** [comment]
Two major issues here:

 - `user` should come from a call to `getuid()` followed by a `getpwuid()` call on all POSIX-like platforms; only shells set `$USER`/`$LOGNAME`, and it should never be relied upon
 - `home` should come from first checking `$HOME` (as this does) or, if that's not present, the return value of the above-mentioned `getpwuid()` call. Under **no circumstances** should hardcoded paths be used. 

And a minor issue:

 - It seems odd to check `process.platform` here; what about BSD or Solaris users? If you're using `getpwuid()` correctly, it should work on all non-win32/wow64 platforms

I just wasted a significant amount of time debugging why gulp (which includes 5 different versions of `os-homedir` on npm < 3) is broken when running out of completely-normal configs that just happen to not look like the author's personal computer.

**Comment by pravi** [comment]
@sindresorhus This issue popped up when packaging os-homedir for debian https://lists.debian.org/debian-devel/2016/10/msg00433.html

Can you please fix this, so that I can package os-homedir and grunt for debian?

**Comment by isaacs** [comment]
So, in all cases where the home fit will be set incorrectly, you are using a node version that doesn't expose the preferred functions for looking up the users home directory. If you dont have homeboy set in the env, and don't have access to getpwuid, then what do you expect a program to do that would be less broken?

Debian (or anyone) can get around this quite easily by shipping a modern node version, in which case the problematic code is never run. 

I fail to see the emergency or even the bug here.

**Comment by ilyash** [comment]
How is that code that returns wrong results is not a bug?

> This is so wrong, I would like to ask that this package not be allowed
> into Debian until it's fixed.

**Comment by isaacs** [comment]
> How is that code that returns wrong results is not a bug?

@ilyash It only returns wrong results in the extremely avoidable case where all of the following are true:

1. An outdated version of node is in use.
2. The `HOME` environment variable is not set.  (Note: this also tends to cause lots of other problems for many terminal programs.)
3. The home directory is not the extremely common `/home/$USER` on Linux, or `/Users/$USER` on Darwin, or `/root` for uid=0.

Is Debian shipping Node 0.10?  Does it fail to set `$HOME` in most cases?  Does it have home directories other than `/home/$USER`?

If not, then this bug does not affect Debian.  If so, it can easily avoid it by upgrading to a (supported!) version of Node.js.  Note that this support also includes security updates (which 0.10 is not receiving, iirc), so it's quite important to do that asap anyway.

**Comment by Roguelazer** [comment]
Those things have nothing to do with a distribution. Someone who's running, say, `gulp` in a clean shell environment (without `$HOME`, which is how many tools invoke build systems) on node 0.10 (because, say, it's required for some project which has a longer lifespan than node's ADD-driven release cycle) will have a completely inscrutable failure because this tool is making incorrect assumptions.

If it's impossible to fix on node 0.10, then the correct thing to do is to raise an error if `$HOME` is unset and indicate that your tool is unable to determine the home directory.

**Comment by isaacs** [comment]
These are all "bugs in theory", but I don't see anyone pointing to an actual example of this happening in real life.  Without that, it's hard for me (at least) to see much urgency with this.

@Roguelazer 

> some project which has a longer lifespan than node's ADD-driven release cycle

First of all, I completely understand that it can be costly and complicated to upgrade the version of a platform that is in use.  That's why polyfills like this one exist in the first place.  At npm, we are in the process of upgrading off of 0.10.  It's not trivial, but it is an important part of operational hygiene.  When using polyfills for unsupported versions, one should expect that some edge cases (such as unsetting the `HOME` environment variable while also having unconventional home directories) may cause strange behavior.  Polyfills are never perfect.

I get from context that you're implying that Node.js has a sporadic and unpredictable release cycle.  First of all, that's untrue.  Node's release cycle is [extremely well-documented](https://github.com/nodejs/LTS), and provides for a 2.5 year maintenance window for all LTS branches.  0.10 drops out of that window next week.

Using attention deficit disorder as a pejorative term is an extremely offensive remark that adds to the pervasive stigma surrounding neurodiversity and mental health.  Please consider how offhand remarks like this can cause real harm to actual human beings, especially when you are communicating with strangers in a public forum.  If the moral argument does not sway you, then consider that unprofessional remarks like that reduce your credibility and thus reduce your ability to influence the behavior of people who you are trying to convince.

As an example of this, I am no longer interested in continuing this conversation.

@sindresorhus, I recommend that you lock this issue.

**Comment by Roguelazer** [comment]
I'm sorry; you're right that was an offensive and inappropriate term.

However, I still strongly feel that widely used modules should not make incorrect and inappropriate assumptions about their operating environment. If you don't know the correct answer, guessing and making the next downstream library crash is worse than returning an explicit exception indicating that you don't know the answer.

Any system user on any Linux or BSD based operating system will have a homedir that isn't in `/home`. If you go look in `/etc/passwd` on any box you have access to, I guarantee that you will find that the majority of home directories are not in `/home`.

**Comment by SamVerschueren** [comment]
@sindresorhus Feel free to reopen, closing it as a precaution before things get out of hand.
